name: CI

on:
    pull_request: []
    push:
        branches:
        - master

jobs:
    unittest:
        runs-on: ${{ matrix.os }}-latest
        name: ${{ matrix.py-version }} Unittest + Coverage (${{ matrix.os }})
        strategy:
            fail-fast: false
            matrix:
                py-version:
                - "2.7"
                - "3.6"
                - "3.7"
                - "3.8"
                - "pypy2"
                - "pypy3"
                os:
                - windows
                - macOS
                - ubuntu
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Setup ${{ matrix.py-version }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.py-version }}

            - name: Install dependencies
              run: pip install -r requirements.txt coverage

            - name: Unittest via coverage
              run: coverage run -m unittest discover

            - name: Results
              run: |
                  coverage report
                  coverage html

            - name: Upload htmlcov
              uses: actions/upload-artifact@v1.0.0
              with:
                  name: htmlcov
                  path: htmlcov

            # # See https://github.com/marketplace/actions/coveralls-github-action
            # - name: Coveralls
            #   uses: coverallsapp/github-action@master
            #   with:
            #       github-token: ${{ secrets.GITHUB_TOKEN }}
            #       path-to-lcov: ./.coverage

            # - name: Coveralls python
            #   if: failure()
            #   run: coveralls